const FrogsData = [
  {
    _title: "蛙蛙项目1",
    _description:
      "蛙蛙项目1描述描述描述描述描述描述描述描述描述描述描述描述蛙蛙项目1描述描述描述描述描述描述描述描述描述描述描述描述蛙蛙项目1描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目2",
    _description: "蛙蛙项目2描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目3",
    _description: "蛙蛙项目3描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目4",
    _description: "蛙蛙项目4描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目5",
    _description: "蛙蛙项目5描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目6",
    _description: "蛙蛙项目6描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目7",
    _description: "蛙蛙项目7描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目8",
    _description: "蛙蛙项目8描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目9",
    _description: "蛙蛙项目9描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目10",
    _description: "蛙蛙项目10描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目11",
    _description: "蛙蛙项目11描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目12",
    _description: "蛙蛙项目12描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目13",
    _description: "蛙蛙项目13描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目14",
    _description: "蛙蛙项目14描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目15",
    _description: "蛙蛙项目15描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目16",
    _description: "蛙蛙项目16描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目17",
    _description: "蛙蛙项目17描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目18",
    _description: "蛙蛙项目18描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目19",
    _description: "蛙蛙项目19描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
  {
    _title: "蛙蛙项目20",
    _description: "蛙蛙项目20描述描述描述描述描述描述描述描述描述描述描述描述",
    _link: "https://baidu.com",
    _gaolAmount: 50,
    _deadline: "2024-06-30",
  },
];

export { FrogsData };
